product_name = "AstraBrew Launcher"
identifier = "cn.astrabrew.launcher"
version = "0.0.1"

icons = ["icons/icon.icns"]

out_dir = "dist"

# 使用我们自己 lipo 合并出来的 Universal Binary
binaries_dir = "target/universal/release"

[macos]
minimum_system_version = "10.15"